name: rounded_input_button
description: A custom widget consisting of a TextField and a Button
version: 0.0.1
repository: https://github.com/neurothrone/rounded_input_button

environment:
  sdk: '>=3.0.1 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
